apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-python-basic-6sto
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-python-basic-6sto
    app.kubernetes.io/part-of: test-app-lrly
  name: devfile-sample-python-basic-6sto
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: python-app
      app.kubernetes.io/instance: devfile-sample-python-basic-6sto
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: python-app
        app.kubernetes.io/instance: devfile-sample-python-basic-6sto
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/build-e2e-bjhz-tenant/test-app-lrly/devfile-sample-python-basic-6sto@sha256:816a4a48d5493748c300567e539d39b986a47cdd70a5669e97c7f36f35021c50
        name: my-python
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
